steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--build-arg'
      - 'VITE_API_URL=${_VITE_API_URL}'
      - '-t'
      - '${_IMAGE}'
      - '.'

images:
  - '${_IMAGE}'

substitutions:
  _VITE_API_URL: 'http://localhost:8000'
  _IMAGE: placeholder

options:
  logging: CLOUD_LOGGING_ONLY
